steps:
    # build the container images
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/cra-cloud-run', './']

    # push the container images to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/cra-cloud-run']
      
    # Deploy container images to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        [
          'run',
          'deploy',
          'cra-cloud-run',
          '--image',
          'gcr.io/$PROJECT_ID/cra-cloud-run',
          '--region',
          'us-central1',
          '--platform',
          'managed',
          '--quiet',
          '--allow-unauthenticated',
        ]
images:
  - gcr.io/$PROJECT_ID/cra-cloud-run
